version: "3"
services:
  app:
    container_name: backcontainer
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/control_empleados
      - DATABASE_USERNAME root
      - DATABASE_PASSWORD root
    depends_on:
      - mysqldb

  mysqldb:
    container_name: "mysqldb"
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "control_empleados"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
volumes:
  mysql-data:
    external: false